"""bank2ai, helpers for banks building MCP servers.

The library exposes:

* a Pydantic data model layer (`bank2ai.models`) shared by every bank2ai
  MCP server, and
* a reusable MCP tool surface (`bank2ai.tools`) (`register_tools`) so each
  bank only has to supply async handlers backed by their own APIs.
"""

from .tools import (
    Handler,
    register_tools,
)
from .models import (
    Account,
    AccountIdentifier,
    AccountList,
    AccountNumberIdentifier,
    AccountStatus,
    AccountType,
    AccountUsage,
    AliasIdentifier,
    AliasType,
    BbanIdentifier,
    CANONICAL_CATEGORY_IDS,
    Category,
    CategoryList,
    CreateRecipientResponse,
    ExecuteTransferDetail,
    ExecuteTransferResponse,
    GetTransactionResponse,
    IbanIdentifier,
    NationalId,
    NationalIdType,
    Party,
    Recipient,
    RecipientList,
    RemittanceInformation,
    Transaction,
    TransactionCode,
    TransactionDirection,
    TransactionList,
    TransactionOrder,
    TransactionStatus,
    TransactionsSummary,
    TransactionsSummaryGroup,
    TransactionsSummaryPeriod,
    TransferAction,
    TransferPreparedItem,
    TransferPreparedResponse,
)

__all__ = [
    "Account",
    "AccountIdentifier",
    "AccountList",
    "AccountNumberIdentifier",
    "AccountStatus",
    "AccountType",
    "AccountUsage",
    "AliasIdentifier",
    "AliasType",
    "BbanIdentifier",
    "CANONICAL_CATEGORY_IDS",
    "Category",
    "CategoryList",
    "CreateRecipientResponse",
    "ExecuteTransferDetail",
    "ExecuteTransferResponse",
    "GetTransactionResponse",
    "Handler",
    "IbanIdentifier",
    "NationalId",
    "NationalIdType",
    "Party",
    "Recipient",
    "RecipientList",
    "RemittanceInformation",
    "Transaction",
    "TransactionCode",
    "TransactionDirection",
    "TransactionList",
    "TransactionOrder",
    "TransactionStatus",
    "TransactionsSummary",
    "TransactionsSummaryGroup",
    "TransactionsSummaryPeriod",
    "TransferAction",
    "TransferPreparedItem",
    "TransferPreparedResponse",
    "register_tools",
]
