"""bank2ai, helpers for banks building MCP servers.

The library exposes:

* a Pydantic data model layer (`bank2ai.models`) shared by every bank2ai
  MCP server, and
* a reusable MCP tool surface (`bank2ai.tools`) (`register_tools`) so each
  bank only has to supply async handlers backed by their own APIs.
"""

from .tools import (
    Handler,
    register_tools,
)
from .models import (
    Account,
    AccountIdentifier,
    AccountList,
    AccountNumberIdentifier,
    AccountStatus,
    AccountType,
    AccountUsage,
    AliasIdentifier,
    AliasType,
    Balance,
    BalanceType,
    BbanIdentifier,
    CANONICAL_CATEGORY_IDS,
    Category,
    CategoryList,
    ConfirmationOfPayee,
    ConfirmationOfPayeeStatus,
    CreateRecipientResponse,
    ExecuteTransferResponse,
    ExecutedTransfer,
    GetTransactionResponse,
    IbanIdentifier,
    NationalId,
    NationalIdType,
    Party,
    PostalAddress,
    PrepareTransferResponse,
    PreparedTransfer,
    Rail,
    Recipient,
    RecipientList,
    RemittanceInformation,
    Transaction,
    TransactionDirection,
    TransactionList,
    TransactionOrder,
    TransactionsSummary,
    TransactionsSummaryGroup,
    TransactionsSummaryPeriod,
    TransferAction,
    TransferExecutionStatus,
    TransferFee,
    TransferFx,
    TransferSummary,
    TransferWarning,
    TransferWarningSeverity,
)

__all__ = [
    "Account",
    "AccountIdentifier",
    "AccountList",
    "AccountNumberIdentifier",
    "AccountStatus",
    "AccountType",
    "AccountUsage",
    "AliasIdentifier",
    "AliasType",
    "Balance",
    "BalanceType",
    "BbanIdentifier",
    "CANONICAL_CATEGORY_IDS",
    "Category",
    "CategoryList",
    "ConfirmationOfPayee",
    "ConfirmationOfPayeeStatus",
    "CreateRecipientResponse",
    "ExecuteTransferResponse",
    "ExecutedTransfer",
    "GetTransactionResponse",
    "Handler",
    "IbanIdentifier",
    "NationalId",
    "NationalIdType",
    "Party",
    "PostalAddress",
    "PrepareTransferResponse",
    "PreparedTransfer",
    "Rail",
    "Recipient",
    "RecipientList",
    "RemittanceInformation",
    "Transaction",
    "TransactionDirection",
    "TransactionList",
    "TransactionOrder",
    "TransactionsSummary",
    "TransactionsSummaryGroup",
    "TransactionsSummaryPeriod",
    "TransferAction",
    "TransferExecutionStatus",
    "TransferFee",
    "TransferFx",
    "TransferSummary",
    "TransferWarning",
    "TransferWarningSeverity",
    "register_tools",
]
