"""Data models for bank integrations.

Organized by domain across this package's submodules; this re-export
surface is the supported import path for everything in `bank2ai.models`.
"""

from .accounts import (
    Account,
    AccountList,
    AccountStatus,
    AccountType,
    AccountUsage,
    Balance,
    BalanceType,
)
from .identity import (
    AccountIdentifier,
    AccountNumberIdentifier,
    AliasIdentifier,
    AliasType,
    BbanIdentifier,
    IbanIdentifier,
    NationalId,
    NationalIdType,
    Party,
    PostalAddress,
)
from .recipients import (
    CreateRecipientResponse,
    Recipient,
    RecipientList,
)
from .transactions import (
    CANONICAL_CATEGORY_IDS,
    Category,
    CategoryList,
    GetTransactionResponse,
    RemittanceInformation,
    Transaction,
    TransactionDirection,
    TransactionList,
    TransactionOrder,
    TransactionsSummary,
    TransactionsSummaryGroup,
    TransactionsSummaryPeriod,
)
from .transfers import (
    ConfirmationOfPayee,
    ConfirmationOfPayeeStatus,
    ExecuteTransferResponse,
    ExecutedTransfer,
    PrepareTransferResponse,
    PreparedTransfer,
    Rail,
    TransferAction,
    TransferExecutionStatus,
    TransferFee,
    TransferFx,
    TransferSummary,
    TransferWarning,
    TransferWarningSeverity,
)

__all__ = [
    "Account",
    "AccountIdentifier",
    "AccountList",
    "AccountNumberIdentifier",
    "AccountStatus",
    "AccountType",
    "AccountUsage",
    "AliasIdentifier",
    "AliasType",
    "Balance",
    "BalanceType",
    "BbanIdentifier",
    "CANONICAL_CATEGORY_IDS",
    "Category",
    "CategoryList",
    "ConfirmationOfPayee",
    "ConfirmationOfPayeeStatus",
    "CreateRecipientResponse",
    "ExecuteTransferResponse",
    "ExecutedTransfer",
    "GetTransactionResponse",
    "IbanIdentifier",
    "NationalId",
    "NationalIdType",
    "Party",
    "PostalAddress",
    "PrepareTransferResponse",
    "PreparedTransfer",
    "Rail",
    "Recipient",
    "RecipientList",
    "RemittanceInformation",
    "Transaction",
    "TransactionDirection",
    "TransactionList",
    "TransactionOrder",
    "TransactionsSummary",
    "TransactionsSummaryGroup",
    "TransactionsSummaryPeriod",
    "TransferAction",
    "TransferExecutionStatus",
    "TransferFee",
    "TransferFx",
    "TransferSummary",
    "TransferWarning",
    "TransferWarningSeverity",
]
