import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/welcome',
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/concepts',
      ],
    },
    {
      type: 'category',
      label: 'Specification',
      collapsed: false,
      items: [
        'specification/overview',
        {
          type: 'category',
          label: 'Tool surface',
          link: {type: 'doc', id: 'specification/tools/index'},
          items: [{type: 'autogenerated', dirName: 'specification/tools'}],
        },
        {
          type: 'category',
          label: 'Data models',
          link: {type: 'doc', id: 'specification/models/index'},
          items: [{type: 'autogenerated', dirName: 'specification/models'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Python library',
      items: [
        'library/overview',
        'library/register-tools',
        'library/models',
        'library/writing-handlers',
        'library/testing',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/run-the-demo',
        'guides/connect-claude',
        'guides/wrap-a-real-bank',
        'guides/add-a-new-bank',
        'guides/build-a-skill',
      ],
    },
    {
      type: 'category',
      label: 'Marketplace',
      items: [
        'marketplace/overview',
        'marketplace/publishing-a-server',
        'marketplace/publishing-a-skill',
        'marketplace/installing',
      ],
    },
    {
      type: 'doc',
      id: 'enterprise/overview',
      label: 'Commercial implementations',
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/roadmap',
        'resources/changelog',
        'resources/contributing',
      ],
    },
  ],
};

export default sidebars;
